version: "3.7"
services:
  mqtt-broker:
    image: eclipse-mosquitto
    container_name: mqtt-broker
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./config:/mosquitto/config
    restart: unless-stopped

volumes:
  config:

networks:
  default:
    name: mqtt-broker-network
